In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns',300)

In [2]:
df=pd.read_csv("train.csv")

In [3]:
df

appno application country.alpha2        country.name decisiondate  \
0      2052/08     MS WORD             ru  Russian Federation          NaN   
1      4728/07     MS WORD             tr              Turkey          NaN   
2     44135/06     MS WORD             si            Slovenia          NaN   
3      2607/08     MS WORD             ch         Switzerland          NaN   
4     27001/06     MS WORD             ru  Russian Federation          NaN   
...        ...         ...            ...                 ...          ...   
8873  60085/12     MS WORD             ua             Ukraine          NaN   
8874  19857/09     MS WORD             ru  Russian Federation          NaN   
8875  67253/01     MS WORD             ru  Russian Federation          NaN   
8876  26737/95     MS WORD             es               Spain          NaN   
8877  21695/05     MS WORD             pl              Poland          NaN   

                                           docname doctypebranch  \
0                     CASE OF KOKOSHKINA v. RUSSIA       CHAMBER   
1                          CASE OF ÖZCAN v. TURKEY     COMMITTEE   
2               CASE OF DANIJEL PEČNIK v. SLOVENIA       CHAMBER   
3                   CASE OF PALANCI v. SWITZERLAND       CHAMBER   
4     CASE OF AMANAT ILYASOVA AND OTHERS v. RUSSIA       CHAMBER   
...                                            ...           ...   
8873        CASE OF RASHITOV AND OTHERS v. UKRAINE     COMMITTEE   
8874                     CASE OF URMANOV v. RUSSIA     COMMITTEE   
8875                   CASE OF BABUSHKIN v. RUSSIA       CHAMBER   
8876    CASE OF BRUALLA GÓMEZ DE LA TORRE v. SPAIN       CHAMBER   
8877                         CASE OF TUR v. POLAND       CHAMBER   

                                    ecli introductiondate  \
0     ECLI:CE:ECHR:2009:0528JUD000205208              NaN   
1     ECLI:CE:ECHR:2018:0710JUD000472807              NaN   
2     ECLI:CE:ECHR:2012:1018JUD004413506              NaN   
3     ECLI:CE:ECHR:2014:0325JUD000260708              NaN   
4     ECLI:CE:ECHR:2009:1001JUD002700106              NaN   
...                                  ...              ...   
8873  ECLI:CE:ECHR:2018:0329JUD006008512              NaN   
8874  ECLI:CE:ECHR:2016:1011JUD001985709              NaN   
8875  ECLI:CE:ECHR:2007:1018JUD006725301              NaN   
8876  ECLI:CE:ECHR:1997:1219JUD002673795              NaN   
8877  ECLI:CE:ECHR:2007:1023JUD002169505              NaN   

                                                issue.0  \
0                                                   NaN   
1                                                   NaN   
2                                                   NaN   
3                                                   NaN   
4                                                   NaN   
...                                                 ...   
8873                                                NaN   
8874                                                NaN   
8875                                                NaN   
8876  Leases of Urban Property Act, section 135, as ...   
8877                                                NaN   

                                         issue.1 issue.10 issue.11 issue.12  \
0                                            NaN      NaN      NaN      NaN   
1                                            NaN      NaN      NaN      NaN   
2                                            NaN      NaN      NaN      NaN   
3                                            NaN      NaN      NaN      NaN   
4                                            NaN      NaN      NaN      NaN   
...                                          ...      ...      ...      ...   
8873                                         NaN      NaN      NaN      NaN   
8874                                         NaN      NaN      NaN      NaN   
8875                                         NaN      NaN      NaN      NaN   
8876  Royal Decree of 3

In [4]:
df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8878 entries, 0 to 8877
Data columns (total 328 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   appno                              8878 non-null   object 
 1   application                        8878 non-null   object 
 2   country.alpha2                     8878 non-null   object 
 3   country.name                       8878 non-null   object 
 4   decisiondate                       676 non-null    object 
 5   docname                            8878 non-null   object 
 6   doctypebranch                      8878 non-null   object 
 7   ecli                               8878 non-null   object 
 8   introductiondate                   676 non-null    object 
 9   issue.0                            2248 non-null   object 
 10  issue.1                            1185 non-null   object 
 11  issue.10                           21 non-null     obje

In [5]:
def missing_values(data, percentage):

    columns = data.columns
    percent_missing = data.isnull().sum() * 100 / len(data)
    missing_value_df = pd.DataFrame({'column_name': columns,
                                 'percent_missing': percent_missing})
    low_missing=list(missing_value_df[(missing_value_df['percent_missing']>0) & (missing_value_df.percent_missing<10)].column_name)
    print(low_missing)
    missing_drop = list(missing_value_df[missing_value_df.percent_missing>percentage].column_name)
    data = data.drop(missing_drop, axis=1)
    return data

In [6]:
df=missing_values(df,50)

['parties.1']


In [7]:
df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8878 entries, 0 to 8877
Data columns (total 294 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   appno                              8878 non-null   object 
 1   application                        8878 non-null   object 
 2   country.alpha2                     8878 non-null   object 
 3   country.name                       8878 non-null   object 
 4   docname                            8878 non-null   object 
 5   doctypebranch                      8878 non-null   object 
 6   ecli                               8878 non-null   object 
 7   itemid                             8878 non-null   object 
 8   judgementdate                      8878 non-null   object 
 9   kpdate                             8878 non-null   object 
 10  languageisocode                    8878 non-null   object 
 11  originatingbody                    8878 non-null   int6

In [8]:
df=df.dropna()

In [9]:
df['importance'].value_counts()

4    5772
3    2011
1     582
2     509
Name: importance, dtype: int64

In [10]:
## Checking the Categorical features importance
cat_df = df.select_dtypes(include=['object']).copy()

In [11]:
cat_df

appno application country.alpha2        country.name  \
0      2052/08     MS WORD             ru  Russian Federation   
1      4728/07     MS WORD             tr              Turkey   
2     44135/06     MS WORD             si            Slovenia   
3      2607/08     MS WORD             ch         Switzerland   
4     27001/06     MS WORD             ru  Russian Federation   
...        ...         ...            ...                 ...   
8873  60085/12     MS WORD             ua             Ukraine   
8874  19857/09     MS WORD             ru  Russian Federation   
8875  67253/01     MS WORD             ru  Russian Federation   
8876  26737/95     MS WORD             es               Spain   
8877  21695/05     MS WORD             pl              Poland   

                                           docname doctypebranch  \
0                     CASE OF KOKOSHKINA v. RUSSIA       CHAMBER   
1                          CASE OF ÖZCAN v. TURKEY     COMMITTEE   
2               CASE OF DANIJEL PEČNIK v. SLOVENIA       CHAMBER   
3                   CASE OF PALANCI v. SWITZERLAND       CHAMBER   
4     CASE OF AMANAT ILYASOVA AND OTHERS v. RUSSIA       CHAMBER   
...                                            ...           ...   
8873        CASE OF RASHITOV AND OTHERS v. UKRAINE     COMMITTEE   
8874                     CASE OF URMANOV v. RUSSIA     COMMITTEE   
8875                   CASE OF BABUSHKIN v. RUSSIA       CHAMBER   
8876    CASE OF BRUALLA GÓMEZ DE LA TORRE v. SPAIN       CHAMBER   
8877                         CASE OF TUR v. POLAND       CHAMBER   

                                    ecli      itemid judgementdate  \
0     ECLI:CE:ECHR:2009:0528JUD000205208   001-92699    28/05/2009   
1     ECLI:CE:ECHR:2018:0710JUD000472807  001-184490    10/07/2018   
2     ECLI:CE:ECHR:2012:1018JUD004413506  001-113810    18/10/2012   
3     ECLI:CE:ECHR:2014:0325JUD000260708  001-141929    25/03/2014   
4     ECLI:CE:ECHR:2009:1001JUD002700106   001-94585    01/10/2009   
...                                  ...         ...           ...   
8873  ECLI:CE:ECHR:2018:0329JUD006008512  001-181843    29/03/2018   
8874  ECLI:CE:ECHR:2016:1011JUD001985709  001-167104    11/10/2016   
8875  ECLI:CE:ECHR:2007:1018JUD006725301   001-82818    18/10/2007   
8876  ECLI:CE:ECHR:1997:1219JUD002673795   001-58127    19/12/1997   
8877  ECLI:CE:ECHR:2007:1023JUD002169505   001-82921    23/10/2007   

          kpdate languageisocode      originatingbody_name  \
0     28/05/2009             ENG             First Section   
1     10/07/2018             ENG  Second Section Committee   
2     18/10/2012             ENG              Fith Section   
3     25/03/2014             ENG            Second Section   
4     01/10/2009             ENG             First Section   
...          ...             ...                       ...   
8873  29/03/2018             ENG    Fith Section Committee   
8874  11/10/2016             ENG   Third Section Committee   
8875  18/10/2007             ENG             Third Section   
8876  19/12/1997             ENG                   Chamber   
8877  23/10/2007             ENG            Fourth Section   

     originatingbody_type                   parties.0    parties.1  \
0                   Court                  KOKOSHKINA       RUSSIA   
1                   Court                       ÖZCAN       TURKEY   
2                   Court              DANIJEL PEČNIK     SLOVENIA   
3                   Court                     PALANCI  SWITZERLAND   
4                   Court  AMANAT ILYASOVA AND OTHERS       RUSSIA   
...                   ...                         ...          ...   
8873                Court         RASHITOV AND OTHERS      UKRAINE   
8874                Court                     URMANOV       RUSSIA   
8875                Court                   BABUSHKIN       RUSSIA   
8876                Court   BRUALLA GÓMEZ DE LA TORRE        SPAIN   
8877                Court                         TUR  

In [12]:
## From the above we can see the categorical Feature Importance and we can drop those based on that
df.drop(['appno','application','country.alpha2','docname','languageisocode','country.name','parties.1','judgementdate','kpdate','originatingbody_type','parties.0'],axis=1,inplace=True)

In [13]:
cat_df = df.select_dtypes(include=['object']).copy()
num_df = df.select_dtypes(include=['int64']).copy()

In [14]:
corr = num_df.corr()
columns = np.full((corr.shape[0],), True, dtype=bool)
for i in range(corr.shape[0]):
    for j in range(i+1, corr.shape[0]):
        if corr.iloc[i,j] >= 0.9:
            if columns[j]:
                columns[j] = False
selected_columns = num_df.columns[columns]
num_df = num_df[selected_columns]

In [15]:
final_df=pd.concat([cat_df,num_df], axis=1, join="inner")
final_df

doctypebranch                                ecli      itemid  \
0          CHAMBER  ECLI:CE:ECHR:2009:0528JUD000205208   001-92699   
1        COMMITTEE  ECLI:CE:ECHR:2018:0710JUD000472807  001-184490   
2          CHAMBER  ECLI:CE:ECHR:2012:1018JUD004413506  001-113810   
3          CHAMBER  ECLI:CE:ECHR:2014:0325JUD000260708  001-141929   
4          CHAMBER  ECLI:CE:ECHR:2009:1001JUD002700106   001-94585   
...            ...                                 ...         ...   
8873     COMMITTEE  ECLI:CE:ECHR:2018:0329JUD006008512  001-181843   
8874     COMMITTEE  ECLI:CE:ECHR:2016:1011JUD001985709  001-167104   
8875       CHAMBER  ECLI:CE:ECHR:2007:1018JUD006725301   001-82818   
8876       CHAMBER  ECLI:CE:ECHR:1997:1219JUD002673795   001-58127   
8877       CHAMBER  ECLI:CE:ECHR:2007:1023JUD002169505   001-82921   

          originatingbody_name respondent.0  originatingbody  \
0                First Section          RUS                4   
1     Second Section Committee          TUR               26   
2                 Fith Section          SVN               23   
3               Second Section          CHE                5   
4                First Section          RUS                4   
...                        ...          ...              ...   
8873    Fith Section Committee          UKR               29   
8874   Third Section Committee          RUS               27   
8875             Third Section          RUS                6   
8876                   Chamber          ESP                9   
8877            Fourth Section          POL                7   

      respondentOrderEng  sharepointid  typedescription  article=3  article=6  \
0                     38        349418               15          1          0   
1                     47        476616               15          0          0   
2                     43        373194               15          0          1   
3                     46        392525               15          0          0   
4                     38        423100               15          1          0   
...                  ...           ...              ...        ...        ...   
8873                  48        473530               15          0          1   
8874                  38        456937               15          0          0   
8875                  38        340823               15          1          0   
8876                  44        443927               15          0          1   
8877                  35        343850               15          0          1   

      article=P1  article=5  article=8  article=13  article=10  article=2  \
0              0          1          0           0           0          0   
1              0          1          0           0           0          0   
2              0          0          0           1           0          0   
3              0          0          1           0           0          0   
4              0          1          0           1           0          1   
...          ...        ...        ...         ...         ...        ...   
8873           0          0          0           1           0          0   
8874           0          1          0           0           0          0   
8875           0          0          0           0           0          0   
8876           0          0          0           0           0          0   
8877           0          0          0           1           0          0   

      article=34  article=41  article=38  article=35  article=4  article=29  \
0              0           0           0           0          0           0   
1              0           0           0           0          0           0   
2              0           0           0           0          0           0   
3              0           0           0           0          0           0   
4              0           0           0           0          0           0   
...          ...       

In [16]:
x=final_df.iloc[:,:-1]
categorical_feature_mask = x.dtypes==object

In [17]:
categorical_cols = x.columns[categorical_feature_mask].tolist()

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[categorical_cols] = x[categorical_cols].apply(lambda col: le.fit_transform(col))
x[categorical_cols].head(10)

doctypebranch  ecli  itemid  originatingbody_name  respondent.0
0              0  3471    8161                     1            38
1              1  7861    3678                    10            44
2              0  5264    1077                     3            42
3              0  5861    1678                     9             8
4              0  3658    8349                     1            38
5              0   681    5373                     1            19
6              0  1808    6495                     9            35
7              0  2614    7307                     5            17
8              0   543    5232                     9            21
9              0  3158    7858                     9            44

In [19]:
from sklearn.decomposition import PCA
lda = PCA(n_components=35, random_state=45)

In [20]:
lda.fit_transform(x)

array([[-5.14935558e+04,  2.33971527e+03, -1.86046213e+03, ...,
        -1.62198263e-01, -3.28034072e-02,  1.51422107e-02],
       [ 7.58347472e+04, -2.94373319e+01, -1.09163828e+03, ...,
         3.13875450e-01,  5.47110630e-01, -5.58684380e-02],
       [-2.75633483e+04, -4.16323421e+03,  7.67938917e+01, ...,
        -1.01310364e-01,  5.70572980e-02, -7.97555126e-02],
       ...,
       [-6.00982402e+04,  1.65143888e+03, -8.01570073e+02, ...,
        -8.72102323e-02,  8.73909211e-02, -1.64320691e-02],
       [ 4.29041368e+04,  3.46994391e+03,  4.45050929e+03, ...,
        -3.70278213e-02, -6.95654385e-02, -1.64876790e-01],
       [-5.70731963e+04,  1.74757441e+03, -7.47674671e+02, ...,
        -1.25420569e-01,  8.54164140e-02, -4.77829022e-02]])

In [21]:
x

doctypebranch  ecli  itemid  originatingbody_name  respondent.0  \
0                 0  3471    8161                     1            38   
1                 1  7861    3678                    10            44   
2                 0  5264    1077                     3            42   
3                 0  5861    1678                     9             8   
4                 0  3658    8349                     1            38   
...             ...   ...     ...                   ...           ...   
8873              1  7745    3553                     4            45   
8874              1  6874    2691                    12            38   
8875              0  2533    7222                    11            38   
8876              0   305    4990                     0            13   
8877              0  2540    7238                     5            35   

      originatingbody  respondentOrderEng  sharepointid  typedescription  \
0                   4                  38        349418               15   
1                  26                  47        476616               15   
2                  23                  43        373194               15   
3                   5                  46        392525               15   
4                   4                  38        423100               15   
...               ...                 ...           ...              ...   
8873               29                  48        473530               15   
8874               27                  38        456937               15   
8875                6                  38        340823               15   
8876                9                  44        443927               15   
8877                7                  35        343850               15   

      article=3  article=6  article=P1  article=5  article=8  article=13  \
0             1          0           0          1          0           0   
1             0          0           0          1          0           0   
2             0          1           0          0          0           1   
3             0          0           0          0          1           0   
4             1          0           0          1          0           1   
...         ...        ...         ...        ...        ...         ...   
8873          0          1           0          0          0           1   
8874          0          0           0          1          0           0   
8875          1          0           0          0          0           0   
8876          0          1           0          0          0           0   
8877          0          1           0          0          0           1   

      article=10  article=2  article=34  article=41  article=38  article=35  \
0              0          0           0           0           0           0   
1              0          0           0           0           0           0   
2              0          0           0           0           0           0   
3              0          0           0           0           0           0   
4              0          1           0           0           0           0   
...          ...        ...         ...         ...         ...         ...   
8873           0          0           0           0           0           0   
8874           0          0           1           0           0           0   
8875           0          0           0           0           0           0   
8876           0          0           0           0           0           0   
8877           0          0           0           0           0           0   

      article=4  article=29  article=14  article=P12  article=9  article=1  \
0             0           0           0            0          0          0   
1             0           0           0            0          0          0   
2             0           0           0            0          0          0   
3             0           0           0   

In [22]:
y=final_df['importance']
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x=ss.fit_transform(x)

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [24]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((6211, 219), (2663, 219), (6211,), (2663,))

In [25]:
x_train

array([[-0.51993961, -0.88905696,  0.9448792 , ..., -0.02714361,
        -0.01501427, -0.01621757],
       [ 1.46540638,  1.28293555, -0.35191431, ..., -0.02714361,
        -0.01501427, -0.01621757],
       [-0.51993961,  0.87266162, -0.76062678, ..., -0.02714361,
        -0.01501427, -0.01621757],
       ...,
       [ 1.46540638, -0.05601742, -1.69359984, ..., -0.02714361,
        -0.01501427, -0.01621757],
       [-0.51993961,  1.20056847, -0.43584285, ..., -0.02714361,
        -0.01501427, -0.01621757],
       [-0.51993961, -1.64753673,  0.18249578, ..., -0.02714361,
        -0.01501427, -0.01621757]])

In [26]:
from sklearn.metrics import confusion_matrix,classification_report,roc_curve,auc,roc_auc_score,precision_score,f1_score,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier,RandomForestClassifier,AdaBoostClassifier,ExtraTreesClassifier
import xgboost as xgb
from sklearn.model_selection import cross_val_score

In [27]:
LR=LogisticRegression()
DT=DecisionTreeClassifier()
GNB=GaussianNB()
RFC=RandomForestClassifier()
ETC=ExtraTreesClassifier()
GBC=GradientBoostingClassifier()
ABC=AdaBoostClassifier()
KN=KNeighborsClassifier()
SV=SVC()
XGBC=xgb.XGBClassifier()

In [28]:
models = []
models.append(('KNeighborsClassifier', KN))
models.append(('SVC', SV))
models.append(('LogisticRegression', LR))
models.append(('DecisionTreeClassifier', DT))
models.append(('GaussianNB', GNB))
models.append(('RandomForestClassifier', RFC))
models.append(('GradientBoostingClassifier', GBC))
models.append(('ExtraTreesClassifier',ETC))
models.append(('AdaBoostClassifier',ABC))
models.append(('XgbClassifier',XGBC))

In [29]:
Model=[]
score=[]
cvs=[]
rocscore=[]
for name,model in models:
    print("----------------",name,'------------')
    print('\n')
    Model.append(name)
    model.fit(x_train,y_train)
    print(model)
    pre=model.predict(x_test)
    print('\n')
    AS=accuracy_score(y_test,pre)
    print('Accuracy_score=',AS)
    score.append(AS*100)
    print('\n')
    sc=cross_val_score(model,x,y,cv=10,scoring='accuracy').mean()
    print('Cross_val_score=',sc)
    cvs.append(sc*100)
    print('\n')
    print('Classification Report\n',classification_report(y_test,pre))
    print('\n')
    cm=confusion_matrix(y_test,pre)
    print(cm)
    print('\n\n')

---------------- KNeighborsClassifier ------------


KNeighborsClassifier()


Accuracy_score= 0.7949680811115284


Cross_val_score= 0.7902868765044638


Classification Report
               precision    recall  f1-score   support

           1       0.43      0.34      0.38       173
           2       0.32      0.18      0.23       145
           3       0.64      0.63      0.63       605
           4       0.89      0.95      0.92      1740

    accuracy                           0.79      2663
   macro avg       0.57      0.52      0.54      2663
weighted avg       0.77      0.79      0.78      2663



[[  59   17   72   25]
 [  26   26   70   23]
 [  41   34  380  150]
 [  11    5   72 1652]]



---------------- SVC ------------


SVC()


Accuracy_score= 0.8227562898986106


Cross_val_score= 0.8245433285596757


Classification Report
               precision    recall  f1-score   support

           1       0.69      0.27      0.39       173
           2       0.21      0.03      0

In [30]:
result = pd.DataFrame({'Model': Model, 'Accuracy_score': score ,'Cross_val_score':cvs})
result

Model  Accuracy_score  Cross_val_score
0        KNeighborsClassifier       79.496808        79.028688
1                         SVC       82.275629        82.454333
2          LogisticRegression       82.801352        83.321996
3      DecisionTreeClassifier       84.040556        84.200984
4                  GaussianNB       70.484416        70.881197
5      RandomForestClassifier       87.908374        87.931115
6  GradientBoostingClassifier       88.021029        87.829649
7        ExtraTreesClassifier       86.781825        86.804151
8          AdaBoostClassifier       84.829140        84.167314
9               XgbClassifier       88.509200        88.967697

In [31]:
from sklearn.model_selection import RandomizedSearchCV
params={
    "learning_rate"    :[0.05,0.10,0.15,0.20,0.25,0.30],
    "n_estimators"     :[100,150,200,250],
    "max_depth"        :[3, 4, 5, 6, 8, 10, 12, 15],
    "gamma"            :[0.0,0.1,0.2,0.3,0.4]
}

In [32]:
r_search=RandomizedSearchCV(XGBC,param_distributions=params,n_iter=10,scoring='accuracy',n_jobs=-1,cv=10,verbose=3)
r_search.fit(x_train,y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  7.1min finished


RandomizedSearchCV(cv=10,
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           gpu_id=-1, importance_type='gain',
                                           interaction_constraints='',
                                           learning_rate=0.300000012,
                                           max_delta_step=0, max_depth=6,
                                           min_child_weight=1, missing=nan,
                                           monotone_constraints='()',
                                           n_estimators=100, n_jobs=0,
                                           num_p...
                                           objective='multi:softprob',
                                           random_state=0, reg_al

In [33]:
r_search.best_score_

0.8864897401245786

In [34]:
r_search.best_params_

{'n_estimators': 150, 'max_depth': 10, 'learning_rate': 0.25, 'gamma': 0.0}

In [35]:
XGBC1=xgb.XGBClassifier(n_estimators=200, max_depth= 6, learning_rate= 0.3, gamma= 0.3)

In [36]:
XGBC1.fit(x_train,y_train)
pre=XGBC1.predict(x_test)
print('\n')
AS=accuracy_score(y_test,pre)
print('Accuracy_score=',AS)
score.append(AS*100)
print('\n')
sc=cross_val_score(model,x,y,cv=10,scoring='accuracy').mean()
print('Cross_val_score=',sc)
cvs.append(sc*100)
print('\n')
print('Classification Report\n',classification_report(y_test,pre))
print('\n')
cm=confusion_matrix(y_test,pre)
print(cm)
print('\n\n')



Accuracy_score= 0.8839654524971836


Cross_val_score= 0.8896769655788821


Classification Report
               precision    recall  f1-score   support

           1       0.75      0.72      0.73       173
           2       0.60      0.36      0.45       145
           3       0.78      0.79      0.78       605
           4       0.95      0.98      0.96      1740

    accuracy                           0.88      2663
   macro avg       0.77      0.71      0.73      2663
weighted avg       0.88      0.88      0.88      2663



[[ 124    4   35   10]
 [  11   52   71   11]
 [  24   28  479   74]
 [   7    3   31 1699]]





In [50]:
test_data=pd.read_csv('test.csv')

In [51]:
test_data

appno application country.alpha2        country.name decisiondate  \
0      1194/04     MS WORD             mk     North Macedonia          NaN   
1     53865/11     MS WORD             ua             Ukraine          NaN   
2     43838/07     MS WORD             ie             Ireland          NaN   
3     11157/04     MS WORD             ru  Russian Federation          NaN   
4     42443/02     MS WORD             ru  Russian Federation          NaN   
...        ...         ...            ...                 ...          ...   
4755   4345/06     MS WORD             ru  Russian Federation          NaN   
4756  10761/09     MS WORD             si            Slovenia          NaN   
4757    805/09     MS WORD             ro             Romania          NaN   
4758  44711/16     MS WORD             gr              Greece          NaN   
4759  21155/18     MS WORD             at             Austria          NaN   

                                                docname doctypebranch  \
0     CASE OF CAMINSKI v. "THE FORMER YUGOSLAV REPUB...     COMMITTEE   
1                             CASE OF KUSHCH v. UKRAINE       CHAMBER   
2                                 CASE OF O. v. IRELAND     COMMITTEE   
3                CASE OF ANCHUGOV AND GLADKOV v. RUSSIA       CHAMBER   
4                           CASE OF EMINBEYLI v. RUSSIA       CHAMBER   
...                                                 ...           ...   
4755                          CASE OF BURMAGA v. RUSSIA     COMMITTEE   
4756       CASE OF JATAIRWAYS, A.D. BEOGRAD v. SLOVENIA     COMMITTEE   
4757                          CASE OF PASCAL v. ROMANIA       CHAMBER   
4758                     CASE OF DAOUKOPOULOS v. GREECE     COMMITTEE   
4759                      CASE OF VOGLREITER v. AUSTRIA     COMMITTEE   

                                    ecli introductiondate  \
0     ECLI:CE:ECHR:2011:0224JUD000119404              NaN   
1     ECLI:CE:ECHR:2015:1203JUD005386511              NaN   
2     ECLI:CE:ECHR:2012:0119JUD004383807              NaN   
3     ECLI:CE:ECHR:2013:0704JUD001115704              NaN   
4     ECLI:CE:ECHR:2009:0226JUD004244302              NaN   
...                                  ...              ...   
4755  ECLI:CE:ECHR:2016:0920JUD000434506              NaN   
4756  ECLI:CE:ECHR:2014:0703JUD001076109              NaN   
4757  ECLI:CE:ECHR:2012:0417JUD000080509              NaN   
4758  ECLI:CE:ECHR:2018:0712JUD004471116              NaN   
4759  ECLI:CE:ECHR:2019:0919JUD002115518              NaN   

                                                issue.0 issue.1 issue.10  \
0                                                   NaN     NaN      NaN   
1                                                   NaN     NaN      NaN   
2                                                   NaN     NaN      NaN   
3        Articles 32-33,134 and 135 of the Constitution     NaN      NaN   
4     Articles 1, 11, 89, 96 and 122 of the Code of ...     NaN      NaN   
...                                                 ...     ...      ...   
4755                                                NaN     NaN      NaN   
4756                                                NaN     NaN      NaN   
4757                                                NaN     NaN      NaN   
4758                                                NaN     NaN      NaN   
4759                                                NaN     NaN      NaN   

     issue.11 issue.12 issue.13 issue.14 issue.15 issue.16 issue.17 issue.18  \
0         NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1         NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
2         NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
3         NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
4         NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
...       ...      ...      ...      ...      ...      ...      ...  

In [39]:
train_cols = final_df.columns
test_cols = test_data.columns

common_cols = train_cols.intersection(test_cols)
train_not_test = train_cols.difference(test_cols)

In [40]:
common_cols

Index(['doctypebranch', 'ecli', 'itemid', 'originatingbody_name',
       'respondent.0', 'originatingbody', 'respondentOrderEng', 'sharepointid',
       'typedescription', 'article=3',
       ...
       'ccl_article=5', 'ccl_article=6', 'ccl_article=7', 'ccl_article=8',
       'ccl_article=9', 'ccl_article=p1', 'ccl_article=p12', 'ccl_article=p4',
       'ccl_article=p6', 'ccl_article=p7'],
      dtype='object', length=219)

In [41]:
train_not_test

Index(['importance'], dtype='object')

In [42]:
final_df=final_df.iloc[:,:-1]
test_data=test_data[final_df.columns]

In [43]:
#test_data=test_data.dropna()

In [44]:
test_data

doctypebranch                                ecli      itemid  \
0        COMMITTEE  ECLI:CE:ECHR:2011:0224JUD000119404  001-103613   
1          CHAMBER  ECLI:CE:ECHR:2015:1203JUD005386511  001-158963   
2        COMMITTEE  ECLI:CE:ECHR:2012:0119JUD004383807  001-108659   
3          CHAMBER  ECLI:CE:ECHR:2013:0704JUD001115704  001-122260   
4          CHAMBER  ECLI:CE:ECHR:2009:0226JUD004244302   001-91447   
...            ...                                 ...         ...   
4755     COMMITTEE  ECLI:CE:ECHR:2016:0920JUD000434506  001-166733   
4756     COMMITTEE  ECLI:CE:ECHR:2014:0703JUD001076109  001-145231   
4757       CHAMBER  ECLI:CE:ECHR:2012:0417JUD000080509  001-110382   
4758     COMMITTEE  ECLI:CE:ECHR:2018:0712JUD004471116  001-184485   
4759     COMMITTEE  ECLI:CE:ECHR:2019:0919JUD002115518  001-195866   

         originatingbody_name respondent.0  originatingbody  \
0      Fith Section Committee          MKD               29   
1                Fith Section          UKR               23   
2      Fith Section Committee          IRL               29   
3               First Section          RUS                4   
4               First Section          RUS                4   
...                       ...          ...              ...   
4755  Third Section Committee          RUS               27   
4756   Fith Section Committee          SVN               29   
4757            Third Section          ROU                6   
4758  First Section Committee          GRC               25   
4759   Fith Section Committee          AUT               29   

      respondentOrderEng  sharepointid  typedescription  article=3  article=6  \
0                     33        359124               15          0          1   
1                     48        435683               15          1          0   
2                     22        357179               15          0          1   
3                     38        430113               15          0          0   
4                     38        352583               15          0          0   
...                  ...           ...              ...        ...        ...   
4755                  38        455125               15          0          0   
4756                  43        388701               15          0          1   
4757                  37        370388               15          0          0   
4758                  19        476724               15          1          0   
4759                   4        491455               15          0          1   

      article=P1  article=5  article=8  article=13  article=10  article=2  \
0              0          0          0           0           0          0   
1              0          1          0           0           0          0   
2              0          0          0           0           0          0   
3              1          0          0           0           0          0   
4              0          1          0           0           0          0   
...          ...        ...        ...         ...         ...        ...   
4755           0          1          0           0           0          0   
4756           0          0          0           1           0          0   
4757           0          0          1           0           0          0   
4758           0          0          0           1           0          0   
4759           0          0          0           0           0          0   

      article=34  article=41  article=38  article=35  article=4  article=29  \
0              0           0           0           0          0           0   
1              0           0           0           0          0           0   
2              0           0           0           0          0           0   
3              0           1           0           1          0           0   
4              0           1           0           0          0           0   
...          ...         ...       

In [45]:
x_tst=test_data
categorical_feature_mask = x_tst.dtypes==object

In [46]:
categorical_cols = x_tst.columns[categorical_feature_mask].tolist()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x_tst[categorical_cols] = x_tst[categorical_cols].apply(lambda col: le.fit_transform(col))
x_tst[categorical_cols].head(10)

doctypebranch  ecli  itemid  originatingbody_name  respondent.0
0              1  2458     194                     4            30
1              0  3514    1249                     3            45
2              1  2660     395                     4            22
3              0  3012     751                     1            38
4              0  1824    4320                     1            38
5              0  1834    4332                     1            38
6              0  3310    1046                     3            45
7              0  1812    4303                     3             6
8              0  2836     571                     5            35
9              1  2413     146                     2            19

In [47]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_tst=ss.fit_transform(x_tst)

In [48]:
x_tst.shape

(4760, 219)

In [55]:
predict=pd.DataFrame(XGBC1.predict(x_tst),columns=['importance'])
test_data['appno']=test_data['appno'].astype(str)
ind=test_data['appno']
pred=pd.concat([ind,predict], axis=1, join="inner")
np.savetxt('predictions2.txt', pred.values, fmt='%s%d', delimiter=",", header="appno,importance") 

In [58]:
ind1=test_data['appno']
pred=pd.concat([ind1,predict], axis=1, join="inner").to_csv('prediction1.txt',index=False)

In [ ]:
pred.dropindex()